# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cem Gokmen
lang: en
email: cem@cemgokmen.com
description: >-
  Cem Gokmen's Personal Website
tagline: |-
  Computer scientist, francophone,<br>
  extremely amateur hiker & biker<br><br>
  Ph.D. Student @ Stanford University<br>
  Mountain View, CA | Istanbul, TR
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cemgokmen.com"
keywords: [] # TODO
logo: "/assets/img/bio-photo.jpg" # TODO: Provide this

author:
  name: Cem Gokmen
  email: cem@cemgokmen.com
  social:
    linkedin: cgokmen
    github: cgokmen
    twitter: cgokmenAI
    google-scholar: "https://scholar.google.com/citations?hl=en&user=wCiI8oUAAAAJ"
    arxiv: "http://arxiv.org/a/gokmen_c_1"
    orcid: "https://orcid.org/0000-0001-9446-6052"

menu:
  - title: "Home"
    url: /
  - title: "Resume"
    url: /assets/files/Cem_Resume.pdf
#   - title: "Research"
#     url: /research/
#   - title: "Teaching"
#     url: "/teaching/"
#  - title: "Projects"
#    url: /portfolio/
  - title: "Blog"
    url: /blog/

# Add links to the footer.
# Typically you'll want to link to your cookie- or privacy policy (if appliable), etc..
# legal:
#   - title:             Impress
#     url:               /impress/
#   - title:             Cookies Policy
#     url:               /cookies-policy/

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2019, Cem Gokmen. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Time & Date
timezone: America/Los_Angeles
date_format: "%b %-d, %Y"

# Pagination configuration (used by the `blog` layout)
paginate:      5
paginate_path: /blog/page-:num/

# Customizaton
# ========================================================================================

# Sidebar image and theme color of the site.
accent_image:          none
accent_color:          rgb(140, 21, 21) #rgb(79,177,186)

# This is used for the `theme-color` meta tag,
# which changes the background color of the browser UI in certain browsers.
# Defaults to `accent_color`.
theme_color:           rgb(140, 21, 21) #rgb(25,55,71)

# The string encoding which fonts to fetch from Google Fonts.
# See: <https://hydejack.com/docs/configuration/>
google_fonts:          Roboto+Slab:400|Noto+Sans:400,400i,700,700i

# The text font. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font:                  Noto Sans, Helvetica, Arial, sans-serif

# The font used for headings. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif

defaults:
  # `jekyll-seo-tag` will mark collection outputs as `BlogPosting`,
  # but we want them to be `WebPage`s:
  - scope:
      type:            projects
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_categories
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_tags
    values:
      seo:
        type:          WebPage

# 3rd Party Integrations
# ----------------------------------------------------------------------------------------

# Set your Google Analytics id to receive `pageview` events.
# To remove Google Anaylics from your page, remove the line below.
# google_analytics:      UA-XXXXXXXX-X

# Setting a disqus shortname will enable the comment section on
# pages with `comments: true` in the front matter.
# disqus:                <disqus_shortname>

# Setting a tinyletter username will enable the newsletter subscription box.
# tinyletter:            <tinyletter_username>

# Hydejack Settings
# ----------------------------------------------------------------------------------------
# These settings are specific to Hydejack.

hydejack:
  # Configure the order of complementary content on blog posts
  post_addons:         [about, newsletter, related, random]

  # Configure the order of complementary content on project pages
  project_addons:      [about, newsletter, other]

  # If you do not use Google Fonts, set to `true`.
  no_google_fonts:     false

  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external:    true

  # Set to `true` if third party plugins fail to work with dynamically loaded pages
  no_push_state:       false

  # Set to `true` if you want to disable the drawer
  no_drawer:           false

  # Set to `true` to prevent usage of `hy-img` (lazy-loading images).
  no_img:              false

  # Set to `true` if you do not want parts of the css inlined in <head/>
  # This will increase site build speed dramatically!
  no_inline_css:       false

  # Set to `true` if you don't intend on changing the accent color on a per-page basis.
  # This will increase site build speed!
  no_page_style:       false

  # Code blocks and tables "break" the layout by spanning the full available width.
  # Set this to true if you want them to be the same width as other content.
  no_break_layout:     false

  # Set to `true` if you do not want to expose your resume and projects
  # in machine-readable formats.
  no_structured_data:  false

  # You can set this to `true` if you don't want to set the `theme-color` meta tag,
  # This only affects the meta tag, not the color specified in the app manifest.
  no_theme_color:      false

  # Set to `true` when building with the `--lsi` option
  # This will increase site build speed!
  use_lsi:             false

  # When using Google Analytics, set to `true` to display a cookie notice banner.
  # When enabled, no user-related data will be stored until the user gives consent.
  # Note that this works in the PRO version of Hydejack.
  cookies_banner:      false

  # Set to `true` if you would like to add a "Powered by Hydejack" link in the footer.
  # Note that this works in the PRO version of Hydejack.
  advertise:           false

  # Dark Mode for Hydejack
  # Note that this works in the PRO version of Hydejack.
  dark_mode:
    # Set to `true` to always use the dark theme.
    always:            false

    # Set to `true` to use the dark theme based on visitors' local time.
    dynamic:           true
    sunrise:           6
    sunset:            18

    # Set to `true` to allow visitors to switch between light and dark mode.
    icon:              true

  # ⚡️ DANGER ZONE ⚡️
  # ----------------
  # This is an _experimental_ feature.
  # Only use if you know what Service Workers are and how they can impact your site!
  offline:
    enabled:           false
    cache_version:     1


# Collections
# ========================================================================================

collections:
  featured_categories:
    permalink:         /:name/
    output:            true

  featured_tags:
    permalink:         /tag-:name/
    output:            true

  projects:
    permalink:         /projects/:path/
    output:            true

# File inclusion/exclusion
# ========================================================================================

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - "*.gemspec"
  - _js
  - _plugins
  - .sass-cache
include:
  - LICENSE.md


# Plugins
# ========================================================================================

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# Theme
# ---------------------------------------------------------------------------------------

# theme: jekyll-theme-hydejack
remote_theme: qwtel/hydejack@v8.4.0

# SEO Tag
# ---------------------------------------------------------------------------------------

# Where you proof that you own this site (used by jekyll-seo-tag)
# google_site_verification: <verification-id>
# -- or --
# webmaster_verifications:
#   google:              <verification-id>
#   bing:                <verification-id>
#   alexa:               <verification-id>
#   yandex:              <verification-id>

# Used for Twitter cards
# twitter:
#   username:            <shortname>

# Used for Facebook open graph
# facebook:
#   app_id:              <id>
#   publisher:           <id>
#   admins:              <id>

# Used on index and about sites
# social:
#   name:                <firstname> <lastname>
#   links:
#     - https://twitter.com/<username>
#     - https://github.com/<username>

# Other Plugins
# ---------------------------------------------------------------------------------------

optional_front_matter:
  remove_originals:    true

readme_index:
  remove_originals:    true
  with_frontmatter:    true

relative_links:
  collections:         true

titles_from_headings:
  strip_title:         true
  collections:         true

kramdown:
  footnote_backlink:   '&#x21a9;&#xfe0e;'
  math_engine:         mathjax
  math_engine_opts:
    preview:           true
    preview_as_code:   true

compress_html:
  comments:            ["<!-- ", " -->"]
  clippings:           all
  endings:             all
  ignore:
    envs:              [development]

sass:
  style:               compressed

liquid:
  error_mode:       warn
  # strict_filters:   true
  # strict_variables: true
